name: Build and Deploy to EC2

on:
  push:
    branches:
      - main # change if your deploy branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install ajv@6 ajv-keywords@3 --save-dev

      - name: Build app
        run: npm run build

      # Archive ONLY the build output
      - name: Archive production build
        run: |
          if [ -d "build" ]; then
            tar -czf build.tar.gz -C build .
          else
            echo "No build output found!"
            exit 1
          fi

      # Copy the tar to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build.tar.gz"
          target: "/tmp"

      # SSH into EC2, expand build into /var/www/convoflow and restart Nginx
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /var/www/convoflow
            sudo rm -rf /var/www/convoflow/*
            sudo tar -xzf /tmp/build.tar.gz -C /var/www/convoflow
            rm /tmp/build.tar.gz
            sudo systemctl restart nginx
            echo "Deployment complete and Nginx restarted!"
