name: Deploy React App to Ubuntu EC2

on:
  push:
    branches:
      - main # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit on error

            # Ensure the repo exists, else clone it
            if [ ! -d "~/convoflow" ]; then
              git clone git@github.com:varnitj178/ConvoFlow.git ~/convoflow
            fi

            cd ~/convoflow

            # Pull the latest code
            git reset --hard
            git pull origin main

            # Install dependencies and build
            npm install
            npm run build

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Restart the app with PM2
            pm2 describe react-app > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              pm2 restart react-app
            else
              pm2 start "serve -s build -l 3000" --name react-app
            fi

            # Ensure PM2 restarts the app on reboot
            pm2 save
            sudo pm2 startup systemd -u ubuntu --hp /home/ubuntu
          EOF
